-- MySQL Script generated by MySQL Workbench
-- Wed Dec  1 16:06:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bigbangk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bigbangk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bigbangk` DEFAULT CHARACTER SET utf8 ;
USE `bigbangk` ;

-- -----------------------------------------------------
-- Table `bigbangk`.`Wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`Wallet` (
  `walletid` INT NOT NULL,
  `balance` DECIMAL(25,2) NOT NULL,
  `IBAN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`walletid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`Bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`Bank` (
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `walletid` INT NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_Bank_Wallet1_idx` (`walletid` ASC) VISIBLE,
  CONSTRAINT `fk_Bank_Wallet1`
    FOREIGN KEY (`walletid`)
    REFERENCES `bigbangk`.`Wallet` (`walletid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`user` (
  `email` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `insertion` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`adress` (
  `postalcode` INT NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`postalcode`, `number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`client` (
  `BSN` VARCHAR(45) NOT NULL,
  `walletid` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dateofbirth` DATE NOT NULL,
  `postalcode` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_Client_Wallet1_idx` (`walletid` ASC) VISIBLE,
  INDEX `fk_Client_user1_idx` (`email` ASC) VISIBLE,
  INDEX `fk_Client_adress1_idx` (`postalcode` ASC, `number` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Wallet1`
    FOREIGN KEY (`walletid`)
    REFERENCES `bigbangk`.`Wallet` (`walletid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_user1`
    FOREIGN KEY (`email`)
    REFERENCES `bigbangk`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_adress1`
    FOREIGN KEY (`postalcode` , `number`)
    REFERENCES `bigbangk`.`adress` (`postalcode` , `number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`Asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`Asset` (
  `code` VARCHAR(5) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`Wallet_has_Asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`Wallet_has_Asset` (
  `code` VARCHAR(5) NOT NULL,
  `walletId` INT NOT NULL,
  `amount` DECIMAL(40,30) NOT NULL,
  PRIMARY KEY (`code`, `walletId`),
  INDEX `fk_Coin_has_Wallet_Wallet1_idx` (`walletId` ASC) VISIBLE,
  INDEX `fk_Coin_has_Wallet_Coin1_idx` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_Coin_has_Wallet_Coin1`
    FOREIGN KEY (`code`)
    REFERENCES `bigbangk`.`Asset` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coin_has_Wallet_Wallet1`
    FOREIGN KEY (`walletId`)
    REFERENCES `bigbangk`.`Wallet` (`walletid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`Transaction` (
  `transactionid` INT NOT NULL,
  `coinamount` DECIMAL(40,30) NOT NULL,
  `transactionvalue` DECIMAL(40,10) NOT NULL,
  `transactiontime` TIMESTAMP NOT NULL,
  `seller` INT NOT NULL,
  `buyer` INT NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`transactionid`, `seller`, `buyer`),
  INDEX `fk_Transaction_Wallet1_idx` (`seller` ASC) VISIBLE,
  INDEX `fk_Transaction_Wallet2_idx` (`buyer` ASC) VISIBLE,
  INDEX `fk_Transaction_Coin1_idx` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_Wallet1`
    FOREIGN KEY (`seller`)
    REFERENCES `bigbangk`.`Wallet` (`walletid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Wallet2`
    FOREIGN KEY (`buyer`)
    REFERENCES `bigbangk`.`Wallet` (`walletid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Coin1`
    FOREIGN KEY (`code`)
    REFERENCES `bigbangk`.`Asset` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`Order` (
  `orderid` INT NOT NULL,
  `coinamount` DECIMAL(40,30) NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  `placementtime` TIMESTAMP NOT NULL,
  `ordertype` VARCHAR(45) NOT NULL,
  `requistedprice` VARCHAR(45) NOT NULL,
  `walletid` INT NOT NULL,
  PRIMARY KEY (`orderid`),
  INDEX `fk_Orders_Coin1_idx` (`code` ASC) VISIBLE,
  INDEX `fk_Order_Wallet1_idx` (`walletid` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Coin1`
    FOREIGN KEY (`code`)
    REFERENCES `bigbangk`.`Asset` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Wallet1`
    FOREIGN KEY (`walletid`)
    REFERENCES `bigbangk`.`Wallet` (`walletid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`Pricehistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`Pricehistory` (
  `datetime` TIMESTAMP NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`datetime`, `code`),
  INDEX `fk_Price_Coin1_idx` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_Price_Coin1`
    FOREIGN KEY (`code`)
    REFERENCES `bigbangk`.`Asset` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`admin` (
  `adminid` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`adminid`, `email`),
  INDEX `fk_admin_user1_idx` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`email`)
    REFERENCES `bigbangk`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`BankSettings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`BankSettings` (
  `code` VARCHAR(45) NOT NULL,
  `startingcapital` VARCHAR(45) NOT NULL,
  `transactioncosts` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`),
  CONSTRAINT `fk_table1_Bank1`
    FOREIGN KEY (`code`)
    REFERENCES `bigbangk`.`Bank` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bigbangk`.`Pendingorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bigbangk`.`Pendingorder` (
  `walletid` INT NOT NULL,
  `lowerbound` VARCHAR(45) NOT NULL,
  `pendingorderid` VARCHAR(45) NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  `coinamount` VARCHAR(45) NOT NULL,
  INDEX `fk_Trigger_Wallet1_idx` (`walletid` ASC) VISIBLE,
  PRIMARY KEY (`pendingorderid`),
  INDEX `fk_Triggeredparcel_Asset1_idx` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_Trigger_Wallet1`
    FOREIGN KEY (`walletid`)
    REFERENCES `bigbangk`.`Wallet` (`walletid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Triggeredparcel_Asset1`
    FOREIGN KEY (`code`)
    REFERENCES `bigbangk`.`Asset` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'userBigbangk'@'localhost' IDENTIFIED BY 'userBigbangkPW';
GRANT ALL PRIVILEGES ON bigbangk . * TO 'userBigbangk' @'localhost';

